### ISSUE TITLE
Support for auto-send and auto-delete

### ISSUE THREAD

**Issue by lognaturel** [getodk/build#165]
Form-level directives for auto sending and/or auto deleting were recently approved at the XForms spec level: opendatakit/xforms-spec#100

There isn't yet an approved syntax for XLSForm: XLSForm/pyxform#126

**Comment by Dars45** [comment]
Hi
i can access my odk aggregate server when i enter my user and password it
is not working. could you help me guys.
it was working but suddenly i have no longer get my server

**Comment by yanokwa** [comment]
@Dars45 This is a support question that is not related to the issue at hand. Please post it to https://forum.opendatakit.org/c/support.

**Comment by clint-tseng** [comment]
Okay—I'm blocked pending XLSForm/pyxform#126 then unless do-nothing is a reasonable fallback in the meantime.

**Comment by florianm** [comment]
XForms spec: https://getodk.github.io/xforms-spec/#submission-attributes
Example:  `<submission orx:auto-delete="true" orx:auto-send="false">`
Former blocker https://github.com/XLSForm/pyxform/issues/126 is now closed (Issa's comment hidden as outdated ;-) )

Where in the UI should these settings live? Menu > Edit > Form properties is the closest in scope.

**Comment by florianm** [comment]
Feedback needed: https://forum.getodk.org/t/help-me-understand-xforms-auto-send-delete/36290

**Comment by florianm** [comment]
The "select" input could use a dash of bottom margin to make the spacing to the help text identical to the text inputs.
