### ISSUE TITLE
Support media in question prompts

### ISSUE THREAD

**Issue by issa-tseng** [getodk/build#172]
Similar to how XLSForms does it. Cf [this](https://forum.opendatakit.org/t/inputting-image-icons-in-odk-build-forms/9135) thread.

**Comment by baghdadbrian** [comment]
+1 I am in the early stages of looking at implementing ODK for a data gathering project. We believe it could be very helpful to have "example images" in-line with the question, to direct the user as to the content that should be included with the requested image. For the time being I will also look to do this with XLSForms, per the thread that clint referenced.

**Comment by florianm** [comment]
Is this addressed by image labels for questions in v0.4.0 or do we need images for each option of a select_* as per https://github.com/getodk/build/issues/245?

**Comment by florianm** [comment]
Media for select* options are tracked at #245 - closing this as completed and deployed as v0.4.0 to prod.
