### ISSUE TITLE
Add likert appearance to select_one

### ISSUE THREAD

**Issue by issa-tseng** [getodk/build#173]

**Comment by yanokwa** [comment]
According to http://xlsform.org/ref-table, this is attribute will be rendered by Enketo, but not by Collect. And since most Build users use Collect, we should probably add it there first. Can you please file another issue on the Collect repo?

**Comment by clint-tseng** [comment]
Ah, yes! That is why I didn't add Likert in the first place. Definitely not putting this in Build before Collect.

**Comment by lognaturel** [comment]
Likert is available since Collect v1.25.0. https://docs.getodk.org/form-question-types#likert-widget

**Comment by florianm** [comment]
Seeing this is merged, this issue looks like it can be closed.

**Comment by yanokwa** [comment]
Fixed by https://github.com/getodk/build/commit/a4878cf0e860051dfcd55d04eeadf7239266611f
