### ISSUE TITLE
In "Open Form" dialog, misleading error message when no form is selected

### ISSUE THREAD

**Issue by rockydcoder** [getodk/build#189]
When you try to open a form without selecting any form, there is an error message that reads:
"Could not open the form. Please try again in a moment"
This is kind of misleading since the actual message should be:
"No form has been selected"

**Comment by rishabhkalra96** [comment]
Looks like I can handle this issue. Can I work on it?

**Comment by clint-tseng** [comment]
Absolutely; yes please. Let me know if you have trouble with it!

**Comment by florianm** [comment]
Closed in https://github.com/getodk/build/pull/285
