### ISSUE TITLE
Support appearance "bearing" for numeric fields

### ISSUE THREAD

**Issue by florianm** [getodk/build#193]
As per http://docs.opendatakit.org/form-widgets/#bearing-widget

I can manually download a form from ODK Build as XML, add `appearance="bearing"` to an input, then manually upload the XML to ODK Aggregate, and the widget will appear as a button "capture bearing". 

Maybe the bearing apperance could be implemented as an additional "style" option for decimal number widgets?

Current ODK Build output of a `type="decimal"` field:
```
<input ref="/data/bearings/bearing_one">
  <label ref="jr:itext('/data/bearings/bearing_one:label')"/>
  <hint ref="jr:itext('/data/bearings/bearing_one:hint')"/>
</input>
```

Desired output rendering a bearing widget:
```
<input appearance="bearing" ref="/data/bearings/bearing_one">
  <label ref="jr:itext('/data/bearings/bearing_one:label')"/>
  <hint ref="jr:itext('/data/bearings/bearing_one:hint')"/>
</input>
```

**Comment by clint-tseng** [comment]
@lognaturel any objections here?

**Comment by lognaturel** [comment]
Works for me!

Kind of a separate question but I'll plant the seed. Perhaps there could also be a pass-through `appearance` field in the advanced section?

**Comment by clint-tseng** [comment]
Scary. Lots of different transformations that target that field.

**Comment by florianm** [comment]
Side note: tested bearing on four Samsung Galaxy Tab S2 devices, the accuracy is horrifying, with differences of 30-40 degrees while pointing into the same direction. Also very sensitive to presence of metal. We won't need the widget until we find a tablet with trustworthy bearing sensors...
