### ISSUE TITLE
An upload error on "Upload Form to Aggregate"

### ISSUE THREAD

**Issue by TomonoriHoshi** [getodk/build#199]
Dear ODK developers,

Hi. I would like to report an error while uploading form to aggregate.  It might be something wrong in my environment, but please kindly allow me to inform.

1) I was able to upload a form to my Aggregate running in Google App Engine.  I used "https://" option.
2) The same form could NOT be uploaded to my ODK Aggregate running in my office.  I used "http://" option.  Indeed, the RED error message appears on the top of submission pop-up (see the figure below).

So, again, my ODK Aggregate might have some problems.  But please kindly check if people here can use the "http" option of ODK Build or not.

Also, another minor thing i'd like to mention here is the position of "Password" letters.  Currently it appears on the right side of "Username" box.  So, "Password" letters would better be moved to the left side of "Password box" (see the figure below).

Thanks for your dedicated work!

Best,
Tomonori HOSHI

![odk_build_report_hoshi](https://user-images.githubusercontent.com/30429678/37576731-072d7ba6-2b71-11e8-958a-9cb151198381.png)

**Comment by clint-tseng** [comment]
Thanks for the report. I think #198 had something to do with this; after I finish my current push with issues not related to this project I'll push a deployment out the door and we can see if it resolves the issue.

**Comment by florianm** [comment]
Closing for now assuming this issue has been resolved - please let us know if not.
