### ISSUE TITLE
Add media types signature, annotate, draw, selfie, selfie video

### ISSUE THREAD

**Issue by lognaturel** [getodk/build#200]
These should probably be in the "Kind" dropdown for media along with image/audio/video.

These are all appearances on existing types:
Signature: `<upload ref="my_image" appearance="signature" mediatype="image/*">`
Annotate: `<upload ref="my_image" appearance="annotate" mediatype="image/*">`
Draw: `<upload ref="my_image" appearance="draw" mediatype="image/*">`
Selfie: `<upload ref="my_image" appearance="new-front" mediatype="image/*">`
Selfie video: `<upload ref="my_image" appearance="draw" mediatype="video/*">`

Forum request: https://forum.opendatakit.org/t/create-free-form-signatures-in-the-odk-build/6767

**Comment by florianm** [comment]
Deployed to prod in v0.4.0, closing as implemented.
