### ISSUE TITLE
Ongoing maintenance tasks

### ISSUE THREAD

**Issue by yanokwa** [getodk/build#248]
- [x] Write up online deployment steps
- [x] Write up offline deployment steps
- [ ] Decide if staging, release, ansible branches are still needed

**Comment by florianm** [comment]
Deployment steps are documented for now in the `ODK Build test forms` google doc linked in Slack.

**Comment by yanokwa** [comment]
Can you drop the link in your comment. Slack is where things go to die 😂

**Comment by florianm** [comment]
Here is the Google doc with test script, maintenance and deployment steps. How would you feel about adding this to the Build docs, e.g. a refactor of building.md or contributing.md?

**Comment by florianm** [comment]
Here is the Google doc with test script, maintenance and deployment steps. How would you feel about adding this to the Build docs, e.g. a refactor of building.md or contributing.md?
