### ISSUE TITLE
Tell user to "save as" a form imported from file

### ISSUE THREAD

**Issue by florianm** [getodk/build#265]
## Current behaviour
* The current toast instructs a user to "File >> Save" a freshly imported form (from .odkbuild save file).
* File >> Save does not persist a freshly imported form
* File >> Save As does persist a freshly imported file

## Suggested fix
* Instruct user to current app behaviour correctly: Change the wording in the toast to "Form >> Save as..." at a minimum.
* Change app behaviour: Form >> Save should also persist a form like "save as" does if not already in database.

**Comment by lognaturel** [comment]
Am I understanding correctly that you propose to do the wording change now and leave the behavior change for future consideration? Seems good to me.

**Comment by florianm** [comment]
Yep, the quick fix I'd include now is the wording change.
