### ISSUE TITLE
Error pasting select options from MS Excel into options editor

### ISSUE THREAD

**Issue by emmabc404** [getodk/build#311]
![image](https://user-images.githubusercontent.com/63747740/172022393-407b598e-a0fc-42d0-865d-926ccdd8f0c3.png)
![image](https://user-images.githubusercontent.com/63747740/172021818-bbe9b9d5-5369-41c5-acae-3a3010fd7eac.png)
I tried to paste over 300 rows of data from my excel table to the bulk edit table but they all appear in a single row (ie, Transposed). I don't have all the time to entering the data row by row.
 Please help.

**Comment by florianm** [comment]
Hi @emmabc404,

Could you answer a few questions to help us get started:

- What operating system and version do you use?
- What office version do you use?
- Does the problem still occur with only the first two or three rows?
- Can you share the spreadsheet with your original options?
- Did you have this problem with any other options pasted from spreadsheets?

**Comment by florianm** [comment]
@emmabc404 any update on this?

**Comment by florianm** [comment]
Closing this as stale.
 
@emmabc404 if you can give us more information, please comment here and I'll be more than happy to reopen and investigate further.
