### ISSUE TITLE
Add in-app messaging about contributing to the project

### ISSUE THREAD

**Issue by lognaturel** [getodk/build#82]
Something like "Are you a developer? See [the source] and become a contributor!"

This could go different places. One idea is to put it at the very bottom of the right hand bar in a darker gray so it's not too distracting but still quite visible.

**Comment by florianm** [comment]
How about a note in the "About menu"?
![image](https://user-images.githubusercontent.com/762815/148500596-02fa2ac8-0ea8-4dcb-87f6-f90689cefd94.png)

**Comment by lognaturel** [comment]
Great!
